### ISSUE TITLE
Scores roll under to 4 trillion when the inital score is negative

### ISSUE THREAD

**Issue by DefProc** [DefProc/mfuklc#2]
This is because the score is stored as an `unsigned long`. But we need to make sure that the `parseInt()` serial transactions still work for negative numbers, or if it needs to be transferred in binary.

**Comment by oomlout** [comment]
Could also just check that score never goes negative.

ie. Add an incrementScore(int amount) routine to adjust the value.

**Comment by DefProc** [comment]
I'm not against negative scores. but I will have to add the option to display minus signs in the scoreboard code too.

**Comment by DefProc** [comment]
Fixed on the display: 4afb87a

**Comment by DefProc** [comment]
And the score is now held as a signed long
