### ISSUE TITLE
The Registration Station needs a different RFID reader

### ISSUE THREAD

**Issue by amcewen** [DefProc/mfuklc#6]
The one we've used so far belongs to @neilbaddielle, so we either need to buy a new SL030 (easiest option) or write a Node.js module and Node RED node for the PN532 reader I've got (cheaper, but more work).

**Comment by oomlout** [comment]
Shoot me a link to the easiest solution on Aliexpress or eBay and oomlout can foot the bill.

**Comment by DefProc** [comment]
An [SL030](http://skpang.co.uk/catalog/hf-rfid-module-sl030-33v-i2c-p-1065.html) will get us running straight away, without having to produce extra code within the next 2 weeks.

**Comment by oomlout** [comment]
On its way.

**Comment by DefProc** [comment]
Lovely, thank you.

**Comment by DefProc** [comment]
Recieved.
